// import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
// import { Toaster } from "react-hot-toast";
// import Providers from "../Providers";
// import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0 bg-zinc-50 text-stone-800 relative`}
//       >
//         <div className="fixed inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]"></div>
//           <Providers>
//             <Toaster />
//             <Navbar />
//             {children}
//           </Providers>

//       </body>
//     </html>
//   );
// }
// src/app/(main)/layout.js (This is the file to fix)

import Navbar from "@/components/Navbar";
import "../globals.css";
import Footer from "@/components/Footer";

export default function MainAppLayout({ children }) {
  // It should NOT have <html>, <body>, or the background div.
  // It only adds the Navbar.
  return (
    <>
      {/* <Navbar />
      {children}
      <Footer/> */}
      <div className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer /> {/* 2. Add the Footer at the end */}
      </div>
    </>
  );
}